Code.gs
Added a check for a null value of the `FID` tag on events. This way, we aren't deleting events that are on the calendar, but aren't part of the ICS/ICAL file
=> Added check for null tag value #11

Code.gs
=> Handle multiple lines and escaped characters

Code.gs
Hi there, really like your script! I've been using it but sometimes an event is created and i don't know who it's from without investigating further. I thought it would be neat to include the name in the event summary so this code allows for that. Let me know if agree or would like me to change anything. Cheers!
=> Add organiser name to event summary

Code.gs
Fixing #25 (and a small typo).
Cheers;
M.
=> Sanitize event properties before equality check.

Code.gs, EventClass.gs
Adding handling of all day events
=> Handling of all day events

Code.gs
=> Fixed several timezone issues

Code.gs, Helpers.gs, LICENSE.txt, README.md, Settings.gs, String functions.gs, ical.js.gs
- Multicalendar support, merge multiple ical calendars to various google calendars
Option to add sourcecalendar name to event title (if available)
- Support of VTODO-Elements
- Full Recurrence support
RRULE, EXRULE, RDATE, EXDATE, RECURRENCE-ID
- Full mapping of ICAL properties to Google Calendar Event Properties
Attendees (Name, Mail, Response), Status, Sequence, Class, Transp, URL
- EMail notification when an event is updated by the script
- Exponential Backoff to handle API-throttling
- Support any Interval as trigger
=> Latest 'stable' version

Code.gs
Hey! I've noticed a room for two small improvements at your already wonderful script (that was exactly what I was looking for) and decided to do it myself. I don't even know if this is PR-worthy but here it is.
**- Removes a possible failure point**
This one is more useful to guarantee that it may work in the future without any more tweaks. So it's great for other people, in the future. For us is quite useless. But who knows? I won't allow the millennium bug to happen again. :laughing:
**- First run at installation**
When I installed the script, I expected to have the events show up in my calendar right away. I was a bit confused to why that wasn't happening. A quick look at the code made me notice that the first run would be at "howFrequent" minutes after installing. That is not …
=> Small improvements

Code.gs, Helpers.gs
As mentioned in Discord support channel
=> Remove triggers from previous versions

Code.gs, Helpers.gs, appsscript.json, ical.js.gs
=> V8 runtime

Helpers.gs
=> Added exponential backoff to ICS retrieving

Code.gs, Helpers.gs
=> Execution summary email

Helpers.gs
Fix #120 
Changed parseNotificationTime to ignore seconds and return minutes as GCal does not support seconds anyways.
=> Added DateTime support for reminders

Helpers.gs
=> Fix AllDay Recurrence Exceptions

Code.gs, Helpers.gs
Some of my events had a visibility class of private and I wanted to be able to override it to the calendar setting.
=> Default event visibility

Helpers.gs
I moved some code relating to the ICAL event from processEvent to createEvent
=> Moved ICAL code

Code.gs
I share the project between different accounts and it happened that the script did not run for one user as it was already running for another.
=> Changed to UserProperties

Code.gs, Helpers.gs
Minimises the number of times it looks for updates
=> Separate trigger update

Helpers.gs
In some cases, I had some errors and callWithBackoff was trying obstinately even if it was just not possible.
One such case was Quota exceeded.
=> Improvement to callWithBackoff

Helpers.gs
If not present, it currently creates a new calendar with the same name each time I hide the calendar.
=> Hidden target

Code.gs
Global variables that should not be reset between when processing each calendars
=> Reset global variables

Helpers.gs
- Helpers.gs: [Cleanup] Strip extraneous whitespace
- Helpers.sendSummary: [Refactor] Name loop vars more appropriately
- Helpers.sendSummary: [Fix] Include correct values in list item
=> Fix date interpolation in emails

Helpers.gs
Fix multi-value exdate handling with onlyFutureEvents = true
=> multi-value exdates

Helpers.gs
=> Validate color property prior adding

Code.gs, Helpers.gs
Adding more flexibility to script trigger to allow for 5, 10, 15, 30, but also any hour from 1-24 with 24 as max trigger.
=> Trigger flexibility

Helpers.gs
=> Fix recurrence timezone handling

Helpers.gs
=> Process dtend timezone

ical.js.gs
https://github.com/kewisch/ical.js/releases/tag/v2.0.1
=> Bump ical.js to v2.0.1

Helpers.gs
Hopefully catched everything take broke.
=> compatibility with new ical.js

Code.gs, appsscript.json
=> Add permission scopes to appsscript.json + reference to wiki
